### ISSUE TITLE
gpgme + gpg2 issues with multiple keys

### ISSUE THREAD

**Issue by jpprins1** [ossobv/pstore#16]
For example:
```
$ ls /tmp/nonce*
/tmp/nonce_old  /tmp/nonce_new
```
Decrypting with `gpg --decrypt` works fine.

But, with gpg2, it does not:
```
$ gpg2 --decrypt < /tmp/nonce_new | cat -A
gpg: encrypted with 4096-bit RSA key, ID XXX, created 2017-02-16
      "Jelle XXX <XXX>"
gpg: public key decryption failed: Operation cancelled
```
^-- good (escape on the gpg-agent, but with proper pass we get proper output)

versus:
```
$ gpg2 --decrypt < /tmp/nonce_old | cat -A
gpg: encrypted with 2048-bit RSA key, ID XXX, created 2015-09-29
      "Jelle XXX (None) <XXX>"
gpg: decryption failed: No secret key
```
^-- doesn't even ask for gpg-agent password

Killing gpg-agent in between does not help the situation.

The order of the secret-keys matters. The problem was inverted between old/new before removing/re-adding the OLD keys to the keyrings. (Actually, removing the old one didn't help until we copied the gnupg/*.gpg contents to a clean dir.)

Interestingly: `gpg2 --list-secret-keys` does not list the desired OLD key, while it does list more secret keys than one. Perhaps gpg2 --import helps?

**Comment by wdoekes** [comment]
Yes. That fixes it! :)
