### ISSUE TITLE
Dont trigger user error if user is already allowed on entry

### ISSUE THREAD

**Issue by aaboonstra** [ossobv/pstore#18]
```
Machine                   User access
------------------------------------------------------------------------
+ test                      alex, herman, walter

$ pstore test +alex; echo $?
user error: one or more users already allowed
1
```

Would be nice if this could be silently ignored. If you do want to keep reporting this error then a --quiet flag could help.

Other idea could be to make this a warning message and exit with code 0 instead.

**Comment by vilitux** [comment]
Would be great to see this implemented.

**Comment by vilitux** [comment]
Thanks
