### ISSUE TITLE
MySQLdb "utf8" warnings for binary blobs have not been fixed

### ISSUE THREAD

**Issue by wdoekes** [ossobv/pstore#19]
The SQLInsertCompiler and SQLUpdateCompiler use get_placeholder for the `_binary` prefix as seen in 67bf6f61743b252c9cb317c3dccddfd9f9aaa82a, but for SELECT queries, that is not called.

We should probably upgrade the entire thing to latest and greatest Django...

**Comment by hbokh** [comment]
Is the above the reason I see "Invalid utf8 character string"-warnings?
Example:
```
2019-01-28T09:37:10.479318915Z /usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py:114: Warning: Invalid utf8 character string: 'C81202'
2019-01-28T09:37:10.479372189Z   return self.cursor.execute(query, args) 
```

when using `django-pstore` on MySQL version: 5.7.21-20 ?

Reference: [BinaryField value must be declared "binary" in queries to avoid MySQL 5.7+ warning](https://code.djangoproject.com/ticket/26140)

**Comment by wdoekes** [comment]
Correct :(

**Comment by Urth** [comment]
Latest release uses Django 3.1.6
