### ISSUE TITLE
crypto error', 'import failed (imported=0, unchanged=2).

### ISSUE THREAD

**Issue by denefoster** [ossobv/pstore#3]
CryptError: ('crypto error', 'import failed (imported=0, unchanged=2). Try setting os.environ["GNUPGHOME"] to an _existing_ writable path in settings; e.g. "/tmp"')

Get that error from the server no matter what, despite the fact that GNUPGHOME is intact set, and it's created key rings inside of it. 

Any ideas what else is failing or how to determine where it's falling over ?

**Comment by wdoekes** [comment]
No feedback from reporter.
